apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-init
  labels:
    app: express-init
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-init
  template:
    metadata:
      labels:
        app: express-init
    spec:
      containers:
        - name: express-init
          image: 0012535540/express-init:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
