apiVersion: v1
kind: Pod
metadata:
  name: express-init
  labels:
    app: express-init
    tier: api
spec:
  containers:
  - name: express-init
    image: 0012535540/express-init
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
