apiVersion: v1
kind: Service
metadata:
  name: express-init
  labels:
    app: express-init
spec:
  type: NodePort
  selector:
    app: express-init
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30008
